/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.days.two.Day
import org.io.Content
import kotlin.time.measureTime

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

fun main() {
  val content = Content(2).loadPartOne()
  
  val timeTaken_1 = measureTime {
    println(
      "Part 1: ${
        Day().partOne(content)
      }"
    )
  }
  println("Time taken: $timeTaken_1")
  val timeTaken_2 = measureTime {
    println(
      "Part 2: ${
        Day().partTwo(content)
      }"
    )
  }
  println("Time taken: $timeTaken_2")
}
